/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGraficas;

import dadoseclasses.CadastroProduto;

/**
 *
 * @author Izaias
 */
public class ModalCadastroProd extends javax.swing.JFrame {

    /**
     * Creates new form ModalCadastroProd
     */
    public void preencherproduto(CadastroProduto prod){
        jTextField1Codigo.setText(prod.getCodigo());
        jTextField2Produto.setText(prod.getProduto());
        jTextField3CodBarras.setText(prod.getCodigoBarra());
        jTextField4UN.setText(prod.getUN());
        jTextField1PesoBruto.setText(prod.getPesoBruto()+"");
    }
    private TelaMatriz Matriz;
    public ModalCadastroProd(TelaMatriz aThis) {
        this.Matriz = aThis;
        initComponents();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoUN = new javax.swing.JLabel();
        TextoProdutoAtivo = new javax.swing.JLabel();
        BotaoProdutoAtivoSim = new javax.swing.JRadioButton();
        BotaoProdutoAtivoNao = new javax.swing.JRadioButton();
        jTextField1Codigo = new javax.swing.JTextField();
        TextoPesoBruto = new javax.swing.JLabel();
        jTextField2Produto = new javax.swing.JTextField();
        jTextField1PesoBruto = new javax.swing.JTextField();
        TextoCodigo = new javax.swing.JLabel();
        BotaoFinalizar = new javax.swing.JButton();
        jTextField3CodBarras = new javax.swing.JTextField();
        BotaoCancelar = new javax.swing.JButton();
        TextoProduto = new javax.swing.JLabel();
        jTextField4UN = new javax.swing.JTextField();
        TextoCodigoBarras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TextoUN.setText("UN:");

        TextoProdutoAtivo.setText("Produto Ativo?");

        BotaoProdutoAtivoSim.setText("Sim");
        BotaoProdutoAtivoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoProdutoAtivoSimActionPerformed(evt);
            }
        });

        BotaoProdutoAtivoNao.setText("Não");
        BotaoProdutoAtivoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoProdutoAtivoNaoActionPerformed(evt);
            }
        });

        TextoPesoBruto.setText("Peso Bruto:");

        TextoCodigo.setText("Cód:");

        BotaoFinalizar.setText("Finalizar");
        BotaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFinalizarActionPerformed(evt);
            }
        });

        BotaoCancelar.setText("Cancelar");

        TextoProduto.setText("Produto:");

        TextoCodigoBarras.setText("Código Barras:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCodigoBarras)
                    .addComponent(jTextField3CodBarras, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jTextField1Codigo))
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextoPesoBruto))
                            .addComponent(jTextField1PesoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoProdutoAtivo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotaoProdutoAtivoSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoProdutoAtivoNao, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextoProduto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField2Produto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoUN)
                            .addComponent(jTextField4UN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BotaoFinalizar)
                .addGap(34, 34, 34)
                .addComponent(BotaoCancelar)
                .addGap(0, 722, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoCodigo)
                            .addComponent(TextoProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(TextoCodigoBarras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3CodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextoPesoBruto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1PesoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextoUN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4UN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(TextoProdutoAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoProdutoAtivoSim)
                            .addComponent(BotaoProdutoAtivoNao))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoFinalizar)
                    .addComponent(BotaoCancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoProdutoAtivoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoProdutoAtivoSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoProdutoAtivoSimActionPerformed

    private void BotaoProdutoAtivoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoProdutoAtivoNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoProdutoAtivoNaoActionPerformed

    private void BotaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFinalizarActionPerformed
        CadastroProduto cad = new CadastroProduto();
        cad.setCodigo(jTextField1Codigo.getText());
        cad.setProduto(jTextField2Produto.getText());
        cad.setCodigoBarra(jTextField3CodBarras.getText());
        cad.setPesoBruto(Double.parseDouble(jTextField1PesoBruto.getText()));
        cad.setUN((jTextField4UN.getText()));
        Matriz.AdicionarProduto(cad);
        dispose();
    }//GEN-LAST:event_BotaoFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoFinalizar;
    private javax.swing.JRadioButton BotaoProdutoAtivoNao;
    private javax.swing.JRadioButton BotaoProdutoAtivoSim;
    private javax.swing.JLabel TextoCodigo;
    private javax.swing.JLabel TextoCodigoBarras;
    private javax.swing.JLabel TextoPesoBruto;
    private javax.swing.JLabel TextoProduto;
    private javax.swing.JLabel TextoProdutoAtivo;
    private javax.swing.JLabel TextoUN;
    private javax.swing.JTextField jTextField1Codigo;
    private javax.swing.JTextField jTextField1PesoBruto;
    private javax.swing.JTextField jTextField2Produto;
    private javax.swing.JTextField jTextField3CodBarras;
    private javax.swing.JTextField jTextField4UN;
    // End of variables declaration//GEN-END:variables
}
